In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

import tensorflow as tf
import keras as kr
from sklearn.model_selection import train_test_split

import os 
from os import getcwd
from os.path import dirname,abspath
import pathlib as pl

import sys

home_path = "C:\\sebin\\ecg"
git_path = home_path+"\\ecg_data_wfdb"

sys.path.append(git_path)
from use.segment.open import ecgtodf

In [2]:
model = kr.models.load_model("C:\\sebin\\ecg\\ecg_data_wfdb\\model\\save\\02.h5")

In [3]:
data = pd.DataFrame(ecgtodf("C:\\sebin\\ecg\\pick\\model2\\02\\1_all"))

100_1219.csv
100_324.csv
101_1258.csv
101_1299.csv
101_1576.csv
101_293.csv
102_1094.csv
102_1109.csv
102_1208.csv
102_1324.csv
102_1353.csv
102_1437.csv
102_1481.csv
102_1503.csv
102_1525.csv
102_1638.csv
102_1680.csv
102_181.csv
102_1843.csv
102_1877.csv
102_1891.csv
102_2052.csv
102_2162.csv
102_263.csv
102_279.csv
102_343.csv
102_398.csv
102_399.csv
102_430.csv
102_436.csv
102_439.csv
102_477.csv
102_500.csv
102_547.csv
102_549.csv
102_641.csv
102_656.csv
102_744.csv
102_812.csv
102_853.csv
102_874.csv
103_1844.csv
103_968.csv
104_1054.csv
104_106.csv
104_1074.csv
104_1123.csv
104_1176.csv
104_1293.csv
104_1492.csv
104_1508.csv
104_170.csv
104_1767.csv
104_1927.csv
104_2014.csv
104_2040.csv
104_2117.csv
104_2136.csv
104_2176.csv
104_2205.csv
104_221.csv
104_248.csv
104_250.csv
104_252.csv
104_437.csv
104_571.csv
104_644.csv
104_652.csv
104_694.csv
104_832.csv
104_86.csv
104_89.csv
105_1002.csv
105_1432.csv
105_2138.csv
105_226.csv
106_1235.csv
106_1278.csv
106_1307.csv
106_1688.csv

In [4]:
data

0       1       2       3       4       5       6       7       8    \
0    -0.435  -0.415  -0.425   -0.42   -0.43  -0.425  -0.415  -0.405  -0.405   
1     -0.19    -0.2  -0.205   -0.22   -0.22   -0.21  -0.205   -0.21  -0.215   
2    -0.425   -0.44  -0.445  -0.445  -0.435   -0.43   -0.44  -0.445   -0.44   
3    -0.415    -0.4    -0.4  -0.415   -0.41  -0.415   -0.41   -0.41  -0.405   
4     -0.37  -0.375   -0.38  -0.375   -0.37   -0.36   -0.35  -0.365  -0.375   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
495  -0.005   -0.09  -0.125  -0.095  -0.095  -0.085   -0.09   -0.12  -0.155   
496   -0.27  -0.265  -0.255   -0.24   -0.22   -0.21    -0.2  -0.185  -0.185   
497   -0.18   -0.16   -0.15  -0.155  -0.175  -0.175   -0.19  -0.205  -0.205   
498   -0.18  -0.155  -0.145   -0.14  -0.145  -0.135   -0.14   -0.13   -0.14   
499   -0.21   -0.22   -0.22  -0.225  -0.225  -0.205    -0.2   -0.21  -0.205   

        9    ...     278     279     280     281     282     283     284  \
0     -0.42  ...  -0.375  -0.395   -0.41  -0.405  -0.395  -0.375  -0.385   
1     -0.21  ...   -0.13   -0.15  -0.155  -0.145   -0.14  -0.125  -0.125   
2     -0.44  ...   -0.38   -0.37   -0.37   -0.36  -0.365   -0.37  -0.395   
3    -0.405  ...  -0.355  -0.365  -0.375    -0.4   -0.38   -0.37   -0.36   
4     -0.38  ...   -0.31  -0.315  -0.305  -0.305  -0.305  -0.305  -0.325   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
495  -0.205  ...   0.185   0.335    0.49   0.675   0.875   1.085    1.26   
496  -0.185  ...  -0.315  -0.325   -0.31    -0.3   -0.29  -0.285    -0.3   
497  -0.215  ...  -0.225  -0.225  -0.225   -0.24   -0.25  -0.255  -0.255   
498   -0.15  ...  -0.205    -0.2  -0.175   -0.17  -0.165   -0.17  -0.195   
499  -0.215  ...  -0.315   -0.31   -0.31  -0.315  -0.315  -0.315   -0.31   

        285     286 287  
0     -0.39  -0.395   S  
1    -0.145   -0.15   N  
2     -0.39  -0.375   N  
3    -0.375  -0.395   N  
4     -0.33   -0.33   N  
..      ...     ...  ..  
495   1.385   1.395   S  
496    -0.3  -0.305   N  
497  -0.255   -0.24   N  
498   -0.19    -0.2   N  
499    -0.3    -0.3   N  

[500 rows x 288 columns]

In [5]:
record = data.iloc[:,:287]
ann = data.iloc[:,287]

In [6]:
record

0       1       2       3       4       5       6       7       8    \
0    -0.435  -0.415  -0.425   -0.42   -0.43  -0.425  -0.415  -0.405  -0.405   
1     -0.19    -0.2  -0.205   -0.22   -0.22   -0.21  -0.205   -0.21  -0.215   
2    -0.425   -0.44  -0.445  -0.445  -0.435   -0.43   -0.44  -0.445   -0.44   
3    -0.415    -0.4    -0.4  -0.415   -0.41  -0.415   -0.41   -0.41  -0.405   
4     -0.37  -0.375   -0.38  -0.375   -0.37   -0.36   -0.35  -0.365  -0.375   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
495  -0.005   -0.09  -0.125  -0.095  -0.095  -0.085   -0.09   -0.12  -0.155   
496   -0.27  -0.265  -0.255   -0.24   -0.22   -0.21    -0.2  -0.185  -0.185   
497   -0.18   -0.16   -0.15  -0.155  -0.175  -0.175   -0.19  -0.205  -0.205   
498   -0.18  -0.155  -0.145   -0.14  -0.145  -0.135   -0.14   -0.13   -0.14   
499   -0.21   -0.22   -0.22  -0.225  -0.225  -0.205    -0.2   -0.21  -0.205   

        9    ...     277     278     279     280     281     282     283  \
0     -0.42  ...   -0.38  -0.375  -0.395   -0.41  -0.405  -0.395  -0.375   
1     -0.21  ...  -0.125   -0.13   -0.15  -0.155  -0.145   -0.14  -0.125   
2     -0.44  ...  -0.365   -0.38   -0.37   -0.37   -0.36  -0.365   -0.37   
3    -0.405  ...  -0.355  -0.355  -0.365  -0.375    -0.4   -0.38   -0.37   
4     -0.38  ...  -0.295   -0.31  -0.315  -0.305  -0.305  -0.305  -0.305   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
495  -0.205  ...   0.065   0.185   0.335    0.49   0.675   0.875   1.085   
496  -0.185  ...   -0.32  -0.315  -0.325   -0.31    -0.3   -0.29  -0.285   
497  -0.215  ...  -0.225  -0.225  -0.225  -0.225   -0.24   -0.25  -0.255   
498   -0.15  ...   -0.21  -0.205    -0.2  -0.175   -0.17  -0.165   -0.17   
499  -0.215  ...  -0.305  -0.315   -0.31   -0.31  -0.315  -0.315  -0.315   

        284     285     286  
0    -0.385   -0.39  -0.395  
1    -0.125  -0.145   -0.15  
2    -0.395   -0.39  -0.375  
3     -0.36  -0.375  -0.395  
4    -0.325   -0.33   -0.33  
..      ...     ...     ...  
495    1.26   1.385   1.395  
496    -0.3    -0.3  -0.305  
497  -0.255  -0.255   -0.24  
498  -0.195   -0.19    -0.2  
499   -0.31    -0.3    -0.3  

[500 rows x 287 columns]

In [7]:
ann

0      S
1      N
2      N
3      N
4      N
      ..
495    S
496    N
497    N
498    N
499    N
Name: 287, Length: 500, dtype: object

In [8]:
x_train , x_test , y_train , y_test = train_test_split(record,ann,test_size=0.3)

In [9]:
x_train

0       1       2       3       4       5       6       7       8    \
240   2.405   2.395     2.4   2.415     2.4   2.385    2.37   2.365   2.375   
345   -0.68  -0.645  -0.625  -0.595   -0.57  -0.535  -0.495   -0.44  -0.405   
229  -0.005   0.015    0.02    0.03    0.03    0.06    0.09   0.115   0.125   
382  -0.565  -0.575  -0.575   -0.56   -0.55  -0.555  -0.555  -0.565   -0.56   
138  -0.845   -0.87  -0.855  -0.845  -0.845  -0.835   -0.83   -0.83  -0.825   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
337  -0.485   -0.47   -0.46  -0.455   -0.43   -0.41  -0.405   -0.39   -0.37   
241   -0.78  -0.785   -0.75  -0.695  -0.625  -0.605   -0.64  -0.685   -0.72   
378   -0.55   -0.55  -0.555   -0.56  -0.565  -0.555   -0.57  -0.575  -0.565   
339  -0.335  -0.305   -0.27  -0.275  -0.235   -0.21   -0.15   -0.12  -0.085   
499   -0.21   -0.22   -0.22  -0.225  -0.225  -0.205    -0.2   -0.21  -0.205   

        9    ...     277     278     279     280     281     282     283  \
240   2.375  ...    0.83    0.85    0.86   0.845    0.82    0.82     0.8   
345   -0.36  ...  -0.375  -0.335  -0.295   -0.26   -0.23   -0.21  -0.185   
229    0.12  ...   -0.28   -0.28   -0.29  -0.315  -0.305  -0.275  -0.255   
382   -0.56  ...  -0.545   -0.55  -0.525  -0.515  -0.525   -0.53   -0.52   
138   -0.81  ...  -1.365   -1.36   -1.37   -1.36  -1.345   -1.33  -1.335   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
337   -0.35  ...  -0.055  -0.035   -0.02    0.01    0.04   0.055    0.08   
241   -0.72  ...  -0.725  -0.665   -0.65  -0.685   -0.73  -0.725   -0.69   
378   -0.57  ...   -0.68  -0.655   -0.66  -0.645   -0.64  -0.625  -0.605   
339   -0.07  ...  -0.085   -0.08  -0.055   -0.02   0.005    0.03   0.055   
499  -0.215  ...  -0.305  -0.315   -0.31   -0.31  -0.315  -0.315  -0.315   

        284     285     286  
240   0.815    0.81   0.805  
345  -0.165  -0.145   -0.12  
229   -0.25  -0.255  -0.245  
382  -0.525  -0.535   -0.53  
138  -1.325  -1.315   -1.34  
..      ...     ...     ...  
337    0.12   0.145   0.185  
241   -0.64  -0.585   -0.56  
378  -0.605  -0.605  -0.595  
339    0.07    0.09   0.125  
499   -0.31    -0.3    -0.3  

[350 rows x 287 columns]

In [10]:
y_train = pd.DataFrame(y_train)
y_test = pd.DataFrame(y_test)

In [11]:
def x_tensor_input(value):
    x=value.astype(float)
    x=x.to_numpy()
    x_row,x_col = x.shape
    x = x.reshape(x_row,x_col, 1)
    return x

number = [0,1,2,3,4]
label = ['N','S','V','F','Q']

def y_tensor_input(value):
    y=value
    y = y.replace(label,number)
    y=y.to_numpy()
    y_row,y_col = y.shape
    y = y.reshape(y_row,y_col, 1)
    return y

In [12]:
x_train = x_tensor_input(x_train)
x_test = x_tensor_input(x_test)

In [13]:
y_train

287
240   F
345   F
229   F
382   S
138   V
..   ..
337   F
241   F
378   N
339   F
499   N

[350 rows x 1 columns]

In [14]:
x_train

array([[[ 2.405],
        [ 2.395],
        [ 2.4  ],
        ...,
        [ 0.815],
        [ 0.81 ],
        [ 0.805]],

       [[-0.68 ],
        [-0.645],
        [-0.625],
        ...,
        [-0.165],
        [-0.145],
        [-0.12 ]],

       [[-0.005],
        [ 0.015],
        [ 0.02 ],
        ...,
        [-0.25 ],
        [-0.255],
        [-0.245]],

       ...,

       [[-0.55 ],
        [-0.55 ],
        [-0.555],
        ...,
        [-0.605],
        [-0.605],
        [-0.595]],

       [[-0.335],
        [-0.305],
        [-0.27 ],
        ...,
        [ 0.07 ],
        [ 0.09 ],
        [ 0.125]],

       [[-0.21 ],
        [-0.22 ],
        [-0.22 ],
        ...,
        [-0.31 ],
        [-0.3  ],
        [-0.3  ]]])

In [15]:
y_train = y_tensor_input(y_train)
y_test = y_tensor_input(y_test)

In [16]:
y_train

array([[[3]],

       [[3]],

       [[3]],

       [[1]],

       [[2]],

       [[0]],

       [[4]],

       [[4]],

       [[4]],

       [[1]],

       [[1]],

       [[1]],

       [[1]],

       [[2]],

       [[1]],

       [[2]],

       [[1]],

       [[2]],

       [[3]],

       [[2]],

       [[1]],

       [[0]],

       [[2]],

       [[4]],

       [[0]],

       [[4]],

       [[1]],

       [[2]],

       [[2]],

       [[0]],

       [[3]],

       [[2]],

       [[0]],

       [[1]],

       [[0]],

       [[4]],

       [[2]],

       [[4]],

       [[3]],

       [[3]],

       [[2]],

       [[1]],

       [[3]],

       [[2]],

       [[2]],

       [[2]],

       [[4]],

       [[3]],

       [[3]],

       [[0]],

       [[0]],

       [[2]],

       [[0]],

       [[3]],

       [[1]],

       [[1]],

       [[0]],

       [[1]],

       [[0]],

       [[3]],

       [[1]],

       [[0]],

       [[3]],

       [[4]],

       [[1]],

       [[4]],

       [[0

In [17]:
y_test

array([[[0]],

       [[0]],

       [[2]],

       [[0]],

       [[1]],

       [[4]],

       [[0]],

       [[3]],

       [[3]],

       [[3]],

       [[1]],

       [[4]],

       [[0]],

       [[3]],

       [[1]],

       [[4]],

       [[2]],

       [[2]],

       [[1]],

       [[4]],

       [[1]],

       [[0]],

       [[0]],

       [[4]],

       [[4]],

       [[0]],

       [[3]],

       [[4]],

       [[4]],

       [[1]],

       [[3]],

       [[4]],

       [[1]],

       [[2]],

       [[2]],

       [[0]],

       [[2]],

       [[2]],

       [[4]],

       [[4]],

       [[1]],

       [[4]],

       [[3]],

       [[1]],

       [[4]],

       [[0]],

       [[0]],

       [[2]],

       [[1]],

       [[4]],

       [[1]],

       [[3]],

       [[1]],

       [[0]],

       [[3]],

       [[2]],

       [[3]],

       [[3]],

       [[2]],

       [[1]],

       [[4]],

       [[4]],

       [[2]],

       [[3]],

       [[0]],

       [[4]],

       [[0

In [18]:
model.compile(loss='sparse_categorical_crossentropy' ,optimizer='adam',metrics=['accuracy'])

In [19]:
history = model.fit(x_train,y_train,epochs=500)

Epoch 1/500
11/11 [==============================] - 0s 4ms/step - loss: 1.6020 - accuracy: 0.2486
Epoch 2/500
11/11 [==============================] - 0s 4ms/step - loss: 1.5552 - accuracy: 0.2857
Epoch 3/500
11/11 [==============================] - 0s 4ms/step - loss: 1.4675 - accuracy: 0.3229
Epoch 4/500
11/11 [==============================] - 0s 4ms/step - loss: 1.3577 - accuracy: 0.3429
Epoch 5/500
11/11 [==============================] - 0s 5ms/step - loss: 1.2238 - accuracy: 0.4543
Epoch 6/500
11/11 [==============================] - 0s 4ms/step - loss: 1.0874 - accuracy: 0.5857
Epoch 7/500
11/11 [==============================] - 0s 4ms/step - loss: 0.9849 - accuracy: 0.6571
Epoch 8/500
11/11 [==============================] - 0s 4ms/step - loss: 0.8779 - accuracy: 0.7114
Epoch 9/500
11/11 [==============================] - 0s 3ms/step - loss: 0.8056 - accuracy: 0.7514
Epoch 10/500
11/11 [==============================] - 0s 3ms/step - loss: 0.7490 - accuracy: 0.7457
Epoch 11/

In [23]:
model.save(git_path+"\\test\\02\\1.h5")

In [1]:
results = model.evaluate(x_test,y_test)
print(results[0],results[1])

NameError: name 'model' is not defined